micronaut:
  application:
    name: keymanager
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/desafio-pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123456'
jpa.default.properties.hibernate.hbm2ddl.auto: update

config:
  itau:
    ispb: '60701190'

clients:
  erpitau:
    url: 'http://localhost:9091'
  bcb:
    url: 'http://localhost:8082'

ispb.file.path: 'ParticipantesSTRport.csv'
