micronaut:
  application:
    name: keymanager
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/desafio-pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123456'


jpa.default.properties.hibernate.hbm2ddl.auto: update

